### ISSUE TITLE
Child Related Object a User Has No Access To

### ISSUE THREAD

**Issue by tjsully** [douglascayers/sfdc-related-files-lightning#17] opened 2018-09-12 18:55 UTC
Hi Doug.  First off, thank you for this component.  I downloaded the code and, in testing, discovered that, if a user does not have any access to one or more of the specified list of child objects (in my case, Opportunity), an error occurs during object initialization.  I am specifying a list of objects in the configuration of the component in App Builder.  I know the list is correct because it works fine when a user who has at least read access to all specified related objects runs it.  I made a fix to the client controller and was wondering if you would be interested in it.

Also, your code made a great starting point for a similar component I made that handles both files and attachments.  My client is starting a prolonged rollout of lightning, and we will have a period of time where we will have both attachments and files in the system, until everyone is off of Salesforce for Outlook and we convert all attachments to files with Magic Mover.

Many thanks,

tom

**Comment by douglascayers** [comment] 2019-01-28 09:39
Hi @tjsully,

Sorry for the very long delay in following up. Thank you very much for your kind feedback, and I'm glad it's working out for you and you've been able to extend it.

You're welcome to share your code or specific changes you feel would make this project better either as comments on this issue or as a pull request.

Thanks!

**Comment by douglascayers** [comment] 2019-05-19 19:03
I'm not able to reproduce the issue where the component errors if the current user does not have access to a child object. For me, that relationship simply isn't shown in the vertical nav on the left side. I believe this is handled by [this earlier code](https://github.com/douglascayers/sfdc-related-files-lightning/commit/689d6ef0c05cd09fca37b0349450a25b67283cfb#diff-5042143e9ddfc052aea3dedcad57178dR181).

Others have requested ability for this to include attachments and files. I'll close this issue and open a new enhancement request specifically for attachment support.

If you're still having issues where users without access to a child object encounter an error with this component, let me know and I'll reopen this issue.

Thanks

**Closed by douglascayers** 2019-05-19 19:03 UTC
Labels: bug 🐞, enhancement ✨, status/inprogress
